name: Post-Deployment Actions

on:
  deployment_status:
    types: [success]  # Trigger only on successful deployments
  workflow_dispatch:

permissions:
  contents: read  # Required to read repository contents

jobs:
  post-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Get new documentation filenames
      - name: Get new documentation filenames
        id: get_new_files
        run: |
          # Get the last commit hash
          LAST_COMMIT=$(git rev-parse HEAD)

          # Find newly added markdown files in /docs/posts
          NEW_FILES=$(git diff --name-status $LAST_COMMIT~1 $LAST_COMMIT | grep '^A' | awk '{print $2}' | grep '^docs/posts/.*\.md$')

          # Export filenames as a GitHub output
          echo "new_files=$NEW_FILES" >> $GITHUB_ENV

      # Step 4: Echo the new files
      - name: Echo new files
        run: |
          echo "${{ env.new_files }}"
