name: Post-Deployment Actions

on:
  push:
    branches:
      - gh-pages  # Trigger on pushes to the gh-pages branch
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read  # Required to read repository contents

jobs:
  post-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Get new documentation filenames
      - name: Get new documentation filenames
        id: get_new_files
        run: |
          # Check if there are any previous commits
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            # Find newly added markdown files in /docs/posts
            NEW_FILES=$(git diff --name-status HEAD~1 HEAD | grep '^A' | awk '{print $2}' | grep '^docs/posts/.*\.md$')
          else
            NEW_FILES=""
          fi

          # Export filenames as a GitHub output
          echo "new_files=$NEW_FILES" >> $GITHUB_ENV

      # Step 4: Echo the new files
      - name: Echo new files
        run: |
          echo "${{ env.new_files }}"
